### ISSUE TITLE
Modify gates' characteristic in cmvae data generation

### ISSUE THREAD

**Issue by surfii3z** [microsoft/AirSim-Drone-Racing-VAE-Imitation#1]
Hi there,

After reading your paper, I am really interested to use CM-VAE approach to estimate the gate post w.r.t to the quad-rotors. 
Also, I plan to try it on the Game of Drones map. But in that case, I will need to modify the shape/ color of the gate.
Could you please let me know if it is possible to do so?

Thanks

**Comment by rogeriobonatti** [comment]
Hi, in this current release you can change the size of the gates by modifying the scale parameter when spawning the gates, either in the code for generation data for [imitation learning](https://github.com/microsoft/AirSim-Drone-Racing-VAE-Imitation/blob/96aea22bd9fc605a012e554c3e291e0dee8733b6/datagen/action_generator/soccer_datagen.py#L134), or for generating data for [training representations](https://github.com/microsoft/AirSim-Drone-Racing-VAE-Imitation/blob/96aea22bd9fc605a012e554c3e291e0dee8733b6/datagen/img_generator/pose_sampler.py#L82). 

The red color comes from the .pak files that only contain red gates. I might update the repo in the future with the project files so that you can modify all parameters of the gate.

**Comment by surfii3z** [comment]
Thank you!
