### ISSUE TITLE
About evaluating the performance Details of different control policies

### ISSUE THREAD

**Issue by daydreamer2023** [microsoft/AirSim-Drone-Racing-VAE-Imitation#7]
![image](https://user-images.githubusercontent.com/19202609/126024954-107c4d61-daaf-447f-b5a9-2bea474b90ca.png)

How should I evaluate the performance of different control policies in Fig.7 ?
I am a new hand using Airim.
I did not find enough details in the paper and code to reproduce it.
Can you give some clues?

**Comment by rogeriobonatti** [comment]
I did not include the code for this in the repo because I did the evaluation by manually counting the number of gates the drone went through, and manually filling in a spreadsheet before plotting using the "seaborn" library. However, it would also be possible to write some code to automatically generate this evaluation. You would need to set a criterion for resetting the episode, and write something to count when the drone actually goes through the gate by looking at its position.
